### ISSUE TITLE
all APIs options should be visible

### ISSUE THREAD

**Issue by ghost** [jenkinsci/sweagle-plugin#8]
All APIs options should be visible for all tasks.
For example , for upload API: allowDelete (default false), auto approve (default true), encoding, only parent, createSnapshot, ...

**Comment by JoeOffenberg** [comment]
Added a few this round including Snapshot, Allow Delete, and Parent Only will add some more in 1.1 to complete the upload action.

**Comment by JoeOffenberg** [comment]
partially resolved
